services:
    postgres_api_monefy:
        image: postgres
        container_name: postgres_api_monefy
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres_api_monefy:/var/lib/postgresql
        networks:
            - network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - network

    redis:
        container_name: redis
        image: redis
        ports:
            - '6379:6379'

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        platform: linux/amd64
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8082:8081

networks:
    network:
        driver: bridge

volumes:
    postgres_api_monefy:
        driver: local
