DELETE http://localhost:3000/expenses/b11ead0f-94a6-40c0-a523-fb88c7853d4f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoidXNlci5zaWdudXBAZ21haWwuY29tIiwiaWF0IjoxNzI3MjkzNTM2fQ.5POjMbcFGj77Jid2-qfn_8AagHQoMopJ8epsqS1q1ao
