POST http://localhost:3000/reset-password/rabbitmq13@gmail.com/0b95d71d77a6815fba247d709fe3cc29e907604478b1e024
content-type: application/json

{
	"new_password": "newpasswordQWE!123",
	"confirm_new_password": "newpasswordQWE!123"
}
